//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusteri
    {
        public int MusteriID { get; set; }
        public string musteriAd { get; set; }
        public string musteriSoyad { get; set; }
        public string musteriMail { get; set; }
        public int musteriTel { get; set; }
        public string musteriMesaj { get; set; }
        public string musteriIlce { get; set; }
        public string musteriAtikTuru { get; set; }
        public decimal musteriMiktar { get; set; }
    }
}
